<!DOCTYPE html>
<!--[if IE 8]> <html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
<meta charset="utf-8">
<meta name="tdm-reservation" content="1"/>
<meta name="tdm-policy" content="https://opg.optica.org/policies/opg-tdm-policy.json"/>
<meta name="viewport" content="width=device-width" initial-scale="1">
<meta http-equiv="X-UA-Compatible" content="IE=Edge"><script>
var __uzdbm_1 = "958ea8dd-f809-20f4-a92b-97bdd6555b28";var __uzdbm_2 ="MjQ2YjVlNzYtZDNoeS1jNzg1LTIzZjYtYWFlOWE2ZDNlYjdmJDU5LjI5LjI0Ni4x";

  (function(w, d, e, u, c, g, a, b){
    w["SSJSConnectorObj"] = w["SSJSConnectorObj"] || {ss_cid : c, domain_info: "auto"};
    w[g] = function(i, j){w["SSJSConnectorObj"][i] = j};
    a = d.createElement(e);
    a.async = true;
    if(navigator.userAgent.indexOf('MSIE')!==-1
    || navigator.appVersion.indexOf('Trident/') > -1){
    u = u.replace("/advanced/", "/advanced/ie/");
    }
    a.src = u;
    b = d.getElementsByTagName(e)[0];
    b.parentNode.insertBefore(a, b);
    
  })(window,document,"script","https://cdn.perfdrive.com/advanced/stormcaster.js","d3i0","ssConf");
    
    ssConf("c1" , "https://cas.avalon.perfdrive.com");
</script>
<meta name="format-detection" content="telephone=no">
<title>Self-reference quantitative phase microscopy for microfluidic devices</title>
<link title="schema(DC)" rel="schema.dc" href="http://purl.org/dc/elements/1.1/" />
<meta name="dc.date" content="2010-02-15">
<meta name="dc.description" content="This Letter describes a quantitative phase microscopy for microfluidic devices using a simple self-referencing interferometry. Compared with the gross dimensions of the microfluidic device, the microchannel occupies only a small area of the device. Hence, the reference field can be generated by inverting the relative position of the specimen and background. Our system is realized using an extended depth-of-field optics in the form of Michelson interferometry, which allows quantitative phase measurement for an increased depth-of-field without moving objective lens or specimen. Furthermore, the system can be readily converted to a higher signal-to-noise ratio Hilbert phase microscopy thanks to the simultaneous acquisition of double interferograms. The performance of our system is verified using polymer beads, micropatterning poly(dimethylsiloxane) (PDMS), and embryo cells in the microchannels.">
<meta name="dc.identifier" content="doi:10.1364/OL.35.000514">
<meta name="dc.language" content="EN">
<meta property="og:description" content="This Letter describes a quantitative phase microscopy for microfluidic devices using a simple self-referencing interferometry. Compared with the gross dimensions of the microfluidic device, the microchannel occupies only a small area of the device. Hence, the reference field can be generated by inverting the relative position of the specimen and background. Our system is realized using an extended depth-of-field optics in the form of Michelson interferometry, which allows quantitative phase measurement for an increased depth-of-field without moving objective lens or specimen. Furthermore, the system can be readily converted to a higher signal-to-noise ratio Hilbert phase microscopy thanks to the simultaneous acquisition of double interferograms. The performance of our system is verified using polymer beads, micropatterning poly(dimethylsiloxane) (PDMS), and embryo cells in the microchannels.">
<meta property="og:image" content="/images/optica_general_thumbnail.jpg">
<meta property="og:sitename" content="Optica Publishing Group">
<meta property="og:title" content="Self-reference quantitative phase microscopy for microfluidic devices">
<meta property="og:type" content="Article">
<meta property="og:url" content="https://opg.optica.org/ol/abstract.cfm?uri=ol-35-4-514">
<meta name="dc.publisher" content="Optica Publishing Group">
<meta name="dc.rights" content="&amp;#169; 2010 Optical Society of America">
<meta name="dc.source" content="Optics Letters, Vol. 35, Issue 4, pp. 514-516">
<meta name="dc.title" content="Self-reference quantitative phase microscopy for microfluidic devices">
<meta name="citation_abstract_html_url" content="https://opg.optica.org/abstract.cfm?uri=ol-35-4-514">
<meta name="citation_author" content="Jaeduck Jang">
<meta name="citation_author_institution" content="Bio Imaging & Signal Processing Laboratory, Department of Bio and Brain Engineering,Korea Advanced Institute of Science and Technology, Daejeon 305-701, Korea">
<meta name="citation_author" content="Chae Yun Bae">
<meta name="citation_author_institution" content="NanoBiotech Laboratory, Department of Bio and Brain Engineering, Korea Advanced Institute of Science and Technology, Daejeon 305-701, Korea">
<meta name="citation_author" content="Je-Kyun Park">
<meta name="citation_author_institution" content="NanoBiotech Laboratory, Department of Bio and Brain Engineering, Korea Advanced Institute of Science and Technology, Daejeon 305-701, Korea">
<meta name="citation_author" content="Jong Chul Ye">
<meta name="citation_author_institution" content="Bio Imaging & Signal Processing Laboratory, Department of Bio and Brain Engineering,Korea Advanced Institute of Science and Technology, Daejeon 305-701, Korea">
<meta name="citation_doi" content="10.1364/OL.35.000514">
<meta name="citation_firstpage" content="514">
<meta name="citation_fulltext_html_url" content="https://opg.optica.org/viewmedia.cfm?uri=ol-35-4-514&amp;seq=0&amp;html=true">
<meta name="citation_issn" content="1539-4794">
<meta name="citation_issue" content="4">
<meta name="citation_journal_abbrev" content="Opt. Lett., OL">
<meta name="citation_journal_title" content="Optics Letters">
<meta name="citation_keywords" content="Microchannels;Phase contrast;Phase measurement;Phase noise;Phase shift;Spatial light modulators;">
<meta name="citation_language" content="EN">
<meta name="citation_lastpage" content="516">
<meta name="citation_online_date" content="2010/02/09">
<meta name="citation_pdf_url" content="https://opg.optica.org/viewmedia.cfm?uri=ol-35-4-514&amp;seq=0">
<meta name="citation_publication_date" content="2010/02/15">
<meta name="citation_publisher" content="Optica Publishing Group">
<meta name="citation_title" content="Self-reference quantitative phase microscopy for microfluidic devices">
<meta name="citation_volume" content="35">
<!-- Google Tag Manager -->
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=">(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;var n=d.querySelector('[nonce]');
n&&j.setAttribute('nonce',n.nonce||n.getAttribute('nonce'));f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5N7G55X');</script>
<!-- End Google Tag Manager -->
<link rel="icon" href="/favicon.ico?v=2">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="/css/token-input-facebook.css">
<link rel="stylesheet" href="/css/app.min.css?v=05292026">
<!--<link rel="stylesheet" href="/css/search.css"> Second style redefines first in app.css -->
<link rel="stylesheet" href="/css/journal-colors.css">
<link rel="stylesheet" href="/css/tools.css?v=09192021">
<link rel="stylesheet" href="/css/jqueryui/jquery-ui.css">
<link rel="stylesheet" href="/css/jqueryui/jquery-ui-1.10.3.custom.min.css">
<link rel="stylesheet" href="/css/carrousel.css">
<!--[if lt IE 9]>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/vendor/html5shiv.min.js"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/vendor/respond.min.js"></script>
<![endif]-->
<link href="/fonts/fa5pro/css/all.css" rel="stylesheet">
<link href="/fonts/fa7/css/all.css" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600|Noto+Sans:700&amp;subset=latin,greek-ext' rel='stylesheet' type='text/css'>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/vendor/custom.modernizr.js"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="https://scholar.google.com/scholar_js/casa.js" async></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
</head>
<body class="single-article journal-ol">
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5N7G55X"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
<symbol id="right-arrow" viewBox="0 0 7.7 8.89">
<defs>
<style>
.rarrow {
stroke-miterlimit: 10;
}
</style>
</defs>
<title>Expand this Topic</title>
<desc>clickable element to expand a topic</desc>
<polygon class="rarrow" points="0.5 0.87 0.5 8.03 6.7 4.45 0.5 0.87" />
</symbol>
</svg>
<div class="site">
<div class="container">
<div class="alert alert-danger d-none" id="loginErrorAlert" role="alert" aria-live="assertive">
<p class="text-center">
Your token has expired or is invalid. Please log in again to continue. Log in by email links must be used within 10 minutes of receipt.
</p>
</div>
</div>
<nav class="primary--home navbar navbar-inverse hidden-xs p-0 mt-1" aria-label="Global Navigation">
<div class="container">
<div class="user-acct navbar-right d-lg-flex flex-row pt-2">
<div class="d-flex flex-column pt-1 position-relative">
<button id="header-search" class="btn text--right shadow-none" type="button" data-bs-toggle="collapse" data-bs-target="#search-nav" aria-label="start search">
<div style="margin-top:-4px; width:30px; height:30px;border: 0; padding-top:6px;">
<i id="header-search-icon" class="fal fa-search text-white" style="font-size:1em;"></i>
</div>
</button>
<div id="search-nav" class="header-search collapse position-absolute end-100 top-0 p-1 bg-black">
<div class="search-bar input-group main-search">
<form name="nojs" action="/search_noscript.cfm" class="form-inline d-flex">
<input name="q" id="topSearchText" type="text" class="search-text-input form-control input-sm header-search_inputField" placeholder="Search" aria-label="Search">
<div class="input-group-btn header-search_btnGroup d-flex">
<div class="dropdown">
<button class="btn btn-sm btn-dropdown dropdown-toggle btn-topheader" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
<span id="dropdownText">All Publications</span> <span class="caret"></span>
</button>
<ul id="dropdownDesktop" class="dropdown-menu z-index--1000" aria-labelledby="dropdownMenuButton">
<!-- Options to change the button text -->
<li><a class="dropdown-item" href="#" data-search-type="all">All Publications</a></li>
<li><a class="dropdown-item" href="#" data-search-type="site">Site Search</a></li>
</ul>
</div>
<button id="topSearch" type="button" class="btn btn-sm btn-search" aria-label="start search" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Enter a search term or choose options to see advanced search" data-bs-custom-class="custom-tooltip">
<div style="margin-top:-4px; width:30px; height:30px; padding-top:6px;">
<i class="fal fa-search text-white" style="font-size:0.8em;"></i>
</div>
</button>
<button data-bs-toggle="collapse" data-bs-target="#advanced-search-popup" type="button" class="btn text-wrap text--right search-options-header p-0 p__1--xs">Advanced Search</button>
</div>
</form>
</div>
<form id="advanced-search-popup" class="collapse advanced-search-popup">
<div class="row avs-header">
<div class="col-sm-9" style="font-weight:bold;">
<i class="fal fa-filter"></i> SEARCH OPTIONS
</div>
<div class="col-sm-3 close-container">
<div class="close-top"><a href="#" data-bs-toggle="collapse" data-bs-target="#advanced-search-popup" style="color:white;">Close <i class="fal fa-times"></i></a></div>
</div>
</div>
<nav class="nav nav-tabs">
<li role="presentation" class="active">
<a href="#" id="OpgAdvancedSearch">Article Search</a>
</li>
<li role="presentation">
<a href="#" id="ImageBankAdvancedSearch">ImageBank Search</a>
</li>
<li role="presentation">
<a href="#" id="ContentAdvancedSearch">Site Search</a>
</li>
</nav>
<div class="avs-content">
<div class="no-content-search">
<div class="avs_grayout"></div>
<div class="row">
<div class="col-sm-2 avs-label" style="font-weight:bold;">KEYWORDS</div>
<div class="col-sm-8">
<input name="" id="txtSearch" type="text" class="form-control" placeholder="Enter search terms here" aria-label="Enter search terms here" />
<span class="opg-search-only"><input id="chkOtrResource" name="selectionChk" type="checkbox" value="" /> <span class="avs-inline-label-left"><label for="chkOtrResource" style="font-weight:normal;">Only if other supplemental resources are available</label></span></span>
</div>
<div class="col-sm-2 opg-search-only">
<div><input name="chkSearchIn" type="checkbox" id="chk-searchin-metadata" CHECKED /> <span class="avs-inline-label-left"><label for="chk-searchin-metadata" style="font-weight:normal;display:inline;">Title and Abstract</label></span></div>
<div><input name="chkSearchIn" type="checkbox" id="chk-searchin-all"/> <span class="avs-inline-label-left"><label for="chk-searchin-all" style="font-weight:normal;">All text</label></span></div>
</div>
</div>
<div class="row space-top">
<div class="col-sm-2 avs-label" style="font-weight:bold;">AUTHORS</div>
<div class="col-sm-8">
<input type="text" id="authorSearch" class="form-control" placeholder="Enter author names here" aria-label="author names"/>
<span class="small muted">&bull; Use these formats for best results: Smith or J Smith</span>
<span class="small muted"><br>&bull; Use a comma to separate multiple people: J Smith, RL Jones, Macarthur</span>
</div>
<div class="col-sm-2">
<label for="chkAny" style="font-weight:normal;">Any :</label>&nbsp;<input id="chkAny" name="chkAnyAll" type="radio" value="any" checked="checked"/>
<label for="chkAll" style="font-weight:normal;">All :</label>&nbsp;<input id="chkAll" name="chkAnyAll" type="radio" value="all"/>
</div>
</div>
<div class="row space-top">
<div class="col-sm-12">
<div class="avs-help avs-divider">
<a class="avs-help-link" data-action='slide-toggle' data-target='#avsHint1' href="#" title="Help Link">?</a>
<div id="avsHint1" class="avs-help-message">
<strong>Tips for preparing a search:</strong>
<ul>
<li>Keep it simple - don't use too many different parameters.</li>
<li>Separate search groups with parentheses and Booleans. Note the Boolean sign must be in upper-case.
<ul>
<li>Example: (diode OR solid-state) AND laser [search contains "diode" or "solid-state" and laser]</li>
<li>Example: (photons AND downconversion) - pump [search contains both "photons" and "downconversion" but not "pump"]</li>
</ul>
</li>
<li>Improve efficiency in your search by using wildcards.</li>
<ul>
<li>Asterisk ( * ) -- Example: "elect*" retrieves documents containing "electron," "electronic," and "electricity"</li>
<li>Question mark (?) -- Example: "gr?y" retrieves documents containing "grey" or "gray"</li>
</ul>
<li>Use quotation marks " " around specific phrases where you want the entire phrase only.</li>
<li>For best results, use the separate Authors field to search for author names.</li>
<li>Author name searching:
<ul>
<li>Use these formats for best results: Smith or J Smith</li>
<li>Use a comma to separate multiple people: J Smith, RL Jones, Macarthur</li>
<li>Note: Author names will be searched in the keywords field, also, but that may find papers where the person is mentioned, rather than papers they authored.</li>
</ul>
</li>
</ul>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-md-12" style="font-weight:bold;">
SEARCH IN
</div>
</div>
<div class="row space-top">
<div class="col-sm-2">
<input name="selectionChk" id="chkJournals" type="checkbox" class="checkbox" CHECKED> <span class="avs-inline-label-left"><label for="chkJournals" style="font-weight:normal;">Journals</label></span>
</div>
<div class="col-sm-7">
<div class="input-collapse">
<input id="advsJournalsSelector" type="text" class="form-control" placeholder="All journals (type names or look up list)" aria-label="choose journals">
<div class="input-group-btn" name="journal">
<button type="button" class="btn btn-default dropdown-toggle avs-modal-open" data-bs-toggle="dropdown" aria-label="Expand"><span class="caret"></span></button>
</div>
</div>
</div>
<div class="col-sm-3 avs-tiny">
<div class="avs-tiny_field">
<label for="volSearch" style="font-weight:normal;">Vol. </label><input id="volSearch" type="text" class="form-control" placeholder="All" />
</div>
<div class="avs-tiny_field">
<label for="issueSearch" style="font-weight:normal;">Issue </label><input id="issueSearch" type="text" class="form-control" placeholder="All" />
</div>
<div class="avs-tiny_field">
<label for="pageSearch" style="font-weight:normal;">Page </label><input id="pageSearch" type="text" class="form-control" placeholder="All" />
</div>
</div>
</div>
<div class="row space-top-lg opg-search-only">
<div class="col-sm-2">
<input id="chkConferences" type="checkbox" class="checkbox" CHECKED> <span class="avs-inline-label-left"><label for="chkConferences" style="font-weight:normal;">Conferences</label></span>
</div>
<div class="col-sm-7">
<div class="input-collapse">
<input type="text" id="advsProceedingSelector" class="form-control" placeholder="All conferences (type names or look up list)" aria-label="choose conferences">
<div class="input-group-btn" name="proceeding">
<button type="button" class="btn btn-default dropdown-toggle avs-modal-open" data-bs-toggle="dropdown" aria-label="Expand"><span class="caret"></span></button>
</div>
</div>
</div>
<div class="col-sm-3 avs-tiny">
<div class="avs-tiny_field">
<label for="yearSearch" style="font-weight:normal;">Year </label><input id="yearSearch" type="text" class="form-control" placeholder="All" />
</div>
<div class="avs-tiny_field avs-tiny_field--expanded">
<label for="sessionPagerSearch" style="font-weight:normal;">Paper # </label><input id="sessionPagerSearch" type="text" class="form-control" placeholder="All" />
</div>
</div>
</div>
<div class="row space-top-lg opg-search-only d-none">
<div class="col-sm-3 d-none">
<input id="chkReports" type="checkbox" class="checkbox" CHECKED> <span class="avs-inline-label-left"><label for="chkReports" style="font-weight:normal;">Industry Reports</label></span>
</div>
<div class="col">&nbsp;</div>
<div class="col-sm-3 avs-tiny">
<div class="avs-tiny_field avs-tiny_field--expanded">
<label for="reportYearSearch" style="font-weight:normal;">Report Year </label><input id="reportYearSearch" type="text" class="form-control" placeholder="All" />
</div>
</div>
</div>
<div class="row space-top">
<div class="col-md-12">
<div class="avs-help avs-divider"></div>
</div>
</div>
<div class="row space-top">
<div class="col-sm-3" style="font-weight:bold;">PUBLICATION YEARS</div>
<div class="col-sm-5">
<div class="form-inline">
<div class="form-group">
<span class="avs-inline-label-right"><label for="startYear" style="font-weight:normal;">From</label></span>
<input id="startYear" type="text" class="form-control year-inline" placeholder="1917" maxlength="4"/>
<span class="avs-inline-label-left avs-inline-label-right"><label for="endYear" style="font-weight:normal;">To</label></span>
<input id="endYear" type="text" class="form-control year-inline" placeholder="2026" maxlength="4"/>
</div>
</div>
</div>
<div class="col-sm-4">
<div><small class="muted">Enter only one date to search</small></div>
<div><small class="muted">After ("From") or Before ("To")</small></div>
</div>
</div>
<div class="row space-top">
<div class="col-md-12">
<div class="avs-help avs-divider"></div>
</div>
</div>
<div class="avs_topics opg-search-only">
<div class="row space-top mbottom-10">
<div class="col-sm-3" style="font-weight:bold;">OPTICS &amp; PHOTONICS TOPICS</div>
<div class="col-sm-9 input-collapse avs_topics-search">
<a id="browsetopicsbutton" href="#" class="btn btn-default avs_topics-browse-btn purple-border">Browse All Topics</a>
<input type="text" id="advsTopicsSelector" class="form-control avs_topics-search-field" placeholder="Search All Topics" aria-label="Search All Topics"><br/>
</div>
</div>
<div class="row space-top selectedtopicsadv mbottom-10">
<div class="col-md-2"><small class="muted">Selected topics</small></div>
<div class="col-md-10" id="advTopicsSelectedList"></div>
</div>
<div class="row selectedtopicsadv mbottom-10">
<div class="col-md-2"></div>
<div class="col-md-10 muted">
<input id="chkAnyTopic" name="chkAnyAllTopic" type="radio" value="any" checked="checked"/> <label for="chkAnyTopic" style="font-weight:normal;">Find articles with <strong>any</strong> selected topics</label>
&nbsp;&nbsp;<input id="chkAllTopic" name="chkAnyAllTopic" type="radio" value="all"/> <label for="chkAllTopic" style="font-weight:normal;">Find articles with <strong>all</strong> selected topics</label>
</div>
</div>
<div class="row hidden mbottom-20" id="pickTopicsBrowse">
<div class="col-md-12 mbottom-20 ">
<strong>Browse All Topics</strong><br>
Click the <svg class="selection-list_arrow"><use xlink:href="#right-arrow" /></svg> to reveal subtopics. Use the checkbox to select a topic to filter your search.
</div>
<div id="advBrowseTopics" class="col-md-12">
</div>
</div>
<div class="row space-top">
<div class="col-md-12">
<div class="avs-help avs-divider">
<a class="avs-help-link" data-action='slide-toggle' data-target='#avsHint2' href="#" title="Help Link">?</a>
<div id="avsHint2" class="avs-help-message">
<strong>About Optics &amp; Photonics Topics</strong>
<br>Optica Publishing Group developed the Optics and Photonics Topics to help organize its diverse content more accurately by topic area. This topic browser contains over 2400 terms and is organized in a three-level hierarchy. <a href="/thesaurus/default.cfm" target="_blank">Read more.</a>
<br><br>Topics can be refined further in the search results. The Topic facet will reveal the high-level topics associated with the articles returned in the search results.
</div>
</div>
</div>
</div>
</div>
<div class="row space-top opg-search-only">
<div class="col-sm-2" style="font-weight:bold;">SPECIAL COLLECTIONS</div>
<div class="col-sm-5 input-collapse">
<input id="specialcollections_ee" name="specialcollections" type="checkbox" value="ee"/> <label class="avs-inline-label-left" for="specialcollections_ee">Energy and Environmental Optics Express</label><br/>
<input id="specialcollections_el" name="specialcollections" type="checkbox" value="elnotes"/> <label class="avs-inline-label-left" for="specialcollections_el">Application Notes (formerly E&L Notes)</label><br/>
<input id="specialcollections_mem" name="specialcollections" type="checkbox" value="memorandum" />
<label for="specialcollections_mem" class="avs-inline-label-left">Memoranda</label><br />
<input id="specialcollections_op" name="specialcollections" type="checkbox" value="opinion" />
<label for="specialcollections_op" class="avs-inline-label-left">Opinions</label>
</div>
<div class="col-sm-5 input-collapse">
<input id="specialcollections_rev" name="specialcollections" type="checkbox" value="review-article" />
<label for="specialcollections_rev" class="avs-inline-label-left">Reviews</label><br />
<input id="specialcollections_spt" name="specialcollections" type="checkbox" value="spotlight"/> <label class="avs-inline-label-left" for="specialcollections_spt">Spotlight on Optics</label><br/>
<input id="specialcollections_tut" name="specialcollections" type="checkbox" value="tutorial"/> <label class="avs-inline-label-left" for="specialcollections_tut">Tutorials</label><br/>
<input id="specialcollections_ret" name="specialcollections" type="checkbox" value="retrospective"/> <label class="avs-inline-label-left" for="specialcollections_tut">Retrospectives</label>
</div>
</div>
<div class="row space-top opg-search-only">
<div class="col-md-12">
<div class="avs-help avs-divider"></div>
</div>
</div>
<div class="row">
<div class="col-sm-6"><a id="clearFilters" href="#" class="btn btn-default purple-border">Clear my choices above</a></div>
<div class="col-sm-6"><a id="cmdSearch" href="#" class="btn btn-primary pull-right"><strong class="fi-magnifying-glass"></strong>&nbsp; Search</a></div>
</div>
</div>
<div id="contentSearchOnly" class="content-search-only d-none">
<div class="row">
<div class="col-sm-2 avs-label" style="font-weight:bold;">KEYWORDS</div>
<div class="col-sm-8">
<input name="" id="contentSearch" type="text" placeholder="Enter search terms here" aria-label="Enter search terms here" />
</div>
<div class="col-sm-2">
<button id="submitContent" class="btn btn-primary">Search</button>
</div>
</div>
</div>
</div>
<input type="hidden" name="origsearchstr" id="origsearchstr" value=""/>
<input type="hidden" name="facetsearchstr" id="facetsearchstr" value=""/>
<input type="hidden" name="facetavoidstr" id="facetavoidstr" value=""/>
</form>
</div>
</div>
<ul class="manage-user-acct nav navbar-nav d-flex flex-row">
<li class="nav-link pt-1"><a href="#" data-bs-toggle="modal" data-bs-target="#userLogin" id="loginModal" class="p__1--md">LOGIN</a></li>
<li class="nav-link pt-1"><a href="https://prism.optica.org" class="p__1--md">SUBMIT</a></li>
<li class="nav-link pt-1 optica-ai-nav"><a href="/content/optica-ai" class="p__1--md">OPTICA AI</a></li>
</ul>
</div>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=">
function closePopup() {
$.get('/util/close_announcement.cfm', function() {
$('.osap-maintenance-alert').alert('close');
})
}
</script>
</div>
</nav>
<div style="background-color: black;">
<header class="masthead container">
<div>
<div>
<div class="mobile-header">
<a class="skip-nav" href="#content">Skip to content</a>
<div class="primary-branding col-sm-4 col-xs-7">
<a href="https://opg.optica.org" class="primary-brand"><img src="/images/Optica_logo_publishing_hz_rev_rgb.png" alt="Optica Publishing Group" /></a>
</div>
<div class="mobile-nav-toggle visible-xs col-xs-5">
<button type="button" class="mobile-nav-btn navbar-toggle" data-bs-toggle="collapse" data-bs-target="#osaGlobalNav" aria-controls="osaGlobalNav" aria-expanded="false" aria-label="Toggle navigation">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<button type="button" class="mobile-search-btn navbar-toggle" data-bs-toggle="collapse" data-bs-target="#mobile-search" aria-label="start search">
<span class="fal fa-search text-white"></span>
</button>
</div>
</div>
<div class="collapse" id="mobile-search">
<div class="header-search col-sm-9 col-xs-12 d-block d-md-none">
<div class="d-flex w-100">
<input id="topSearchTextMobile" type="text" placeholder="Search" aria-label="Search" style="width:60%">
<div class="input-group-btn d-flex">
<div class="dropdown">
<button class="btn btn-sm btn-dropdown dropdown-toggle btn-topheader" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
<span id="dropdownTextMobile">All Publications</span> <span class="caret"></span>
</button>
<ul id="dropdownMobile" class="dropdown-menu z-index--1000" aria-labelledby="dropdownMenuButton">
<!-- Options to change the button text -->
<li><a class="dropdown-item" href="#" data-search-type="all">All Publications</a></li>
<li><a class="dropdown-item" href="#" data-search-type="site">Site Search</a></li>
</ul>
</div>
<a id="topSearchMobile" class="btn btn-primary btn-sm"><span class="fal fa-search text-white"></span></a>
</div>
</div>
</div>
</div>
<div class="site-nav-container col-lg-8 col-md-12">
<nav class="primary-site-nav collapse navbar-collapse" id="osaGlobalNav" aria-label="Osa Global Navigation">
<ul class="nav navbar-nav navbar-main d-sm-flex flex-sm-row" id="first-nav">
<li class="primary-site-nav__dropdown">
<a href="/about.cfm" class="dropdown-toggle navbar-main-header navbar-aria-header" id="select_journals" role="button" aria-haspopup="true" aria-controls="journalsDropdown" tabindex="0">Journals </a>
<div class="dropdown-menu dropdown-two-col-lg dropdown-wide " id="journalsDropdown">
<div class="row">
<div class="col-md-6 col-sm-12">
<ul>
<li><a href="/aop">Advances in Optics and Photonics</a></li>
<li><a href="/ao">Applied Optics</a></li>
<li><a href="/as">Applied Spectroscopy</a></li>
<li><a href="/boe">Biomedical Optics Express</a></li>
<li><a href="/col">Chinese Optics Letters</a></li>
<li><a href="/copp">Current Optics and Photonics</a></li>
<li><a href="/jlt">Journal of Lightwave Technology</a></li>
<li><a href="/jnirs">Journal of Near Infrared Spectroscopy</a></li>
<li><a href="/jot">Journal of Optical Technology</a></li>
<li><a href="/jocn">Journal of Optical Communications and Networking</a></li>
<li><a href="/josaa">Journal of the Optical Society of America A</a></li>
<li><a href="/josab">Journal of the Optical Society of America B</a></li>
<li><a href="/optica">Optica</a></li>
<li><a href="/opticaq">Optica Quantum</a></li>
</ul>
</div>
<div class="col-md-6 col-sm-12">
<ul>
<li><a href="/ome">Optical Materials Express</a></li>
<li><a href="https://www.optica-opn.org/home/" target="_blank">Optics and Photonics News <span class="fal fa-external-link"></span></a></li>
<li><a href="/optcon">Optics Continuum</a></li>
<li><a href="/oe">Optics Express</a></li>
<li><a href="/ol">Optics Letters</a></li>
<li><a href="/prj">Photonics Research</a></li>
<li class="nav-link-heading"><span class="nav-link-heading-txt">Legacy Journals</span></li>
<li><a href="/jdt">Journal of Display Technology (2005-2016)</a></li>
<li><a href="/josk">Journal of the Optical Society of Korea (1997-2016)</a></li>
<li><a href="/jon">Journal of Optical Networking (2002-2009)</a></li>
<li><a href="/josa">Journal of the Optical Society of America (1917-1983)</a></li>
<li><a href="/on">Optics News (1975-1989)</a></li>
<li><a href="/osac">OSA Continuum (2018-2021)</a></li>
</ul>
</div>
</div>
</div>
</li>
<li class="primary-site-nav__dropdown">
<a href="/conferences.cfm" class="dropdown-toggle navbar-main-header navbar-aria-header" id="select_proceedings" role="button" aria-haspopup="true" aria-controls="conferencesDropdown" tabindex="0">Conferences </a>
<div class="dropdown-menu dropdown-two-col-lg" id="conferencesDropdown">
<div class="row">
<div class="col-sm-6">
<ul>
<li class="nav-link-heading"><span class="nav-link-heading-txt">Find Conferences</span></li>
<li><a href="/conferences.cfm">By Year</a></li>
<li><a href="/conferences.cfm?findby=conference">By Name</a></li>
<li class="nav-link-heading"><span class="nav-link-heading-txt">Featured</span></li>
<li><a href="/conference.cfm?meetingid=5">Optical Fiber Communication (OFC)</a></li>
<li><a href="/conference.cfm?meetingid=124">Conference on Lasers and Electro-Optics (CLEO)</a></li>
<li><a href="/conference.cfm?meetingid=56">Frontiers in Optics (FiO)</a></li>
</ul>
</div>
<div class="col-sm-6">
<ul>
<li class="nav-link-heading"><span class="nav-link-heading-txt">Newly Published</span></li>
<li><a href="/conference.cfm?meetingid=123&yr=2026">CLEO: Applications and Technology</a></li>
<li><a href="/conference.cfm?meetingid=320&yr=2026">CLEO: Fundamental Science</a></li>
<li><a href="/conference.cfm?meetingid=124&yr=2026">CLEO: Science and Innovations</a></li>
<li><a href="/conference.cfm?meetingid=163&yr=2026">Optics and the Brain</a></li>
<li><a href="/conference.cfm?meetingid=5&yr=2026">Optical Fiber Communication Conference</a></li>
</ul>
</div>
</div>
</div>
</li>
<li class="primary-site-nav__dropdown">
<a href="https://opticapreprints.figshare.com/" class="dropdown-toggle navbar-main-header navbar-aria-header" id="select_preprints" role="button" aria-haspopup="true" aria-controls="preprintsDropdown" tabindex="0">Preprints </a>
<div class="dropdown-menu dropdown-two-col-lg" id="preprintsDropdown">
<div class="row">
<div class="col-md-6 col-sm-12">
<ul>
<li class="nav-link-heading"><span class="nav-link-heading-txt">Optica Open</span></li>
<li><a href="https://opticapreprints.figshare.com/" target="_blank">View preprints</a></li>
<li><a href="https://opticaopen.org" target="_blank">Submit preprint</a></li>
<li><a href="https://opticaopen.org/Home/Guidelines" target="_blank">Author instructions</a></li>
</ul>
</div>
<div class="col-md-6 col-sm-12">
<ul>
<li class="nav-link-heading"><span class="nav-link-heading-txt"></span></li>
<li class="nav-link-heading"><span class="nav-link-heading-txt"></span></li>
<li><a href="https://opticaopen.org/Home/About" target="_blank">About</a></li>
<li><a href="https://opticaopen.org/Home/FAQ" target="_blank">FAQ</a></li>
</ul>
</div>
</div>
</div>
</li>
<li class="primary-site-nav__dropdown">
<a href="#global-nav" class="dropdown-toggle navbar-main-header navbar-aria-header" id="select_other_resources" data-bs-toggle="dropdown" data-bs-target="select_other_resources" role="button" aria-haspopup="true" aria-controls="resourcesDropdown" tabindex="0">Other Resources </a>
<div class="dropdown-menu dropdown-two-col-lg" id="resourcesDropdown">
<div class="row">
<div class="col-sm-6">
<ul>
<li class="nav-link-heading"><span class="nav-link-heading-txt">Information For</span></li>
<li><a href="/content/author/">Authors</a></li>
<li><a href="/content/reviewer/">Reviewers</a></li>
<li><a href="/content/library/">Librarians</a></li>
<li class="nav-link-heading"><span class="nav-link-heading-txt">Products and Services</span></li>
<li><a href="/content/info/portal/item/digitalarchive/">Digital Archive</a></li>
<li><a href="/content/collection/page/item/isp/">Interactive Science Publishing (ISP)</a></li>
<li><a href="https://opticapreprints.figshare.com/" target="_blank">Optica Open <span class="fal fa-external-link"></span></a></li>
<li><a href="/info/opticsimagebank.cfm">Optics ImageBank</a></li>
<li><a href="/thesaurus/default.cfm">Optics and Photonics Topics</a></li>
<li><a href="/spotlight">Spotlight on Optics</a></li>	
</ul>
</div>
<div class="col-sm-6">
<ul>
<li class="nav-link-heading"><span class="nav-link-heading-txt">Publications</span></li>
<li><a href="/content/bookshelf/">Bookshelf</a></li>
<li><a href="/collections/special-collections.cfm">Special Collections</a></li>
<li class="nav-link-heading"><span class="nav-link-heading-txt">Regional Content</span></li>
<li><a href="/content/newsItem/list/section/prj/">On The Cover: Photonics Research</a></li>
<li><a href="/content/newsItem/list/section/col/">Spotlight: Chinese Optics Letters</a></li>
<li class="nav-link-heading"><span class="nav-link-heading-txt">Open Access Information</span></li>
<li><a href="/content/author/portal/item/review-open-access-policy-stat/">Open Access Statement and Policy</a>
</li>
<li><a href="/library/license_v2.cfm">Terms for Journal Article Reuse</a></li>
<li class="nav-link-heading"><span class="nav-link-heading-txt">Accessibility Information</span></li>
<li><a href="/content/library/portal/item/accessibility-statement">OPG Accessibility Statement</a>
</li>	
</ul>
</div>
</div>
</div>
</li>
</ul>
<ul class="nav navbar-nav navbar-right navbar-secondary d-sm-flex flex-sm-row" id="second-nav">
<li class="primary-site-nav__dropdown">
<a href="#" class="dropdown-toggle navbar-secondary-header navbar-aria-header" data-bs-toggle="dropdown" id="my_favorites" aria-controls="favoritesDropdown">My Favorites </a>
<div class="dropdown-menu dropdown-one-col" id="favoritesDropdown">
<ul>
<li><a href="/user">Go to My Account</a></li>
<li><a href="#" data-bs-toggle="modal" data-bs-target="#userLogin">Login to access favorites</a></li>
</ul>
</div>
</li>
<li class="primary-site-nav__dropdown">
<a href="#" class="dropdown-toggle navbar-secondary-header navbar-aria-header" data-bs-toggle="dropdown" id="recent_pages" aria-controls="recentsDropdown">Recent Pages </a>
<div class="dropdown-menu dropdown-one-col" id="recentsDropdown">
<ul class="recent-page-list">
</ul>
</div>
</li>
</ul>
<ul class="hidden-sm hidden-md hidden-lg manage-user-acct--mobile">
<li class="nav-link"><a href="#" data-bs-toggle="modal" data-bs-target="#userLogin" id="loginModal"><img src="/images/icons/icon-my-account.png" alt="my account"> LOGIN <span class="muted">OR</span> CREATE ACCOUNT</a>
</ul>
</nav>
</div>
</div>
</div>
</header>
</div>
<nav class="nav-bar-siblings container small">
<a class="secondary-smallnav-item_link" href="/ol/home.cfm">Journal Home</a>
<a class="secondary-smallnav-item_link" href="/ol/journal/ol/about.cfm">About</a>
<a class="secondary-smallnav-item_link" href="/ol/upcomingissue.cfm">Issues in Progress</a>
<a class="secondary-smallnav-item_link" href="/ol/issue.cfm">Current Issue</a>
<a class="secondary-smallnav-item_link" href="/ol/browse.cfm">All Issues</a>
<a class="secondary-smallnav-item_link" href="/ol/upcoming.cfm">Early Posting</a>
</nav>
<div role="main" class="container content d-flex flex-column" id="articleContainer" style="padding-top:1em;">
<div class="col-md-12">
<div class="row">
<div class="article-parents">
<ul class="small list-inline article-journal-name">
<li><strong>Optics Letters</strong></li>
<li>Vol. 35,</li>
<li><a href="/ol/issue.cfm?volume=35&issue=4">Issue 4</a>,</li>
<li>pp. 514-516</li>
<li>(2010)</li>
<li class="article-doi"><span class="separator-disc">&bull;</span><a href="https://doi.org/10.1364/OL.35.000514">https://doi.org/10.1364/OL.35.000514</a></li>
</ul>
</div>
</div>
<div class="row">
<div class="article-header">
<div class="col-md-12 col-sm-12 pl-0">
<div class="col-md-2 col-sm-2 article-header__image p-0" style="">
<div class="w-100 text--left">
<div class="p-0 text--center" style="border:1px solid #ddd;">
<img src="/images/optica_general_thumbnail.jpg" width="168" height="170" alt="Optica Article" class="img-thumbnail hidden-xs article-thumbnail_img jcover">
</div>
</div>
</div>
<div class="col-md-10 col-sm-10 pl-4 mb-1" style="">
<h1 class="article-title" lang="en">
Self-reference quantitative phase microscopy for microfluidic devices
</h1>
<p class="article-authors">
Jaeduck Jang, Chae Yun Bae, Je-Kyun Park, and Jong Chul Ye
</p>
<div>
<div class="btn-group article-affiliations-dropdown dropdown hidden-xs mr-2">
<a data-bs-toggle="dropdown" id="author-affiliations-dropdown">
Author Information <span class="caret"></span>
</a>
<div id="authorAffiliations" class="article-author-affiliations dropdown-menu">
<h5>Author Affiliations</h5>
<p><strong>
Jaeduck Jang,<sup>1</sup>
Chae Yun Bae,<sup>2</sup>
Je-Kyun Park,<sup>2</sup>
and Jong Chul Ye<sup>1,</sup><sup>*</sup>
</strong></p>
<p><em>
<sup>1</sup>Bio Imaging & Signal Processing Laboratory, Department of Bio and Brain Engineering, Korea Advanced Institute of Science and Technology, Daejeon 305-701, Korea
</em></p>
<p><em>
<sup>2</sup>NanoBiotech Laboratory, Department of Bio and Brain Engineering, Korea Advanced Institute of Science and Technology, Daejeon 305-701, Korea
</em></p>
<p>
<sup>*</sup>Corresponding author: <a href="mailto:jong.ye@kaist.ac.kr">jong.ye@kaist.ac.kr</a>
</p>
</div>
</div>
<div class="btn-group hidden-xs hidden-sm">
<a data-bs-toggle="dropdown" id="search-by-author-dropdown">
<i class="fal fa-search p__1--sm"></i> Find other works by these authors <span class="caret"></span>
</a>
<ul class="dropdown-menu" id="search-by-author">
<li><a href="search.cfm?a=J Jang">J Jang</a></li>
<li><a href="search.cfm?a=C Bae">C Bae</a></li>
<li><a href="search.cfm?a=J Park">J Park</a></li>
<li><a href="search.cfm?a=J Ye">J Ye</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-md-12 pr-0">
<div class="col-md-2 pr-0 pl-0">
<a name="scrollUp"></a>
<div class="access-permissions inaccessible" style="margin-left:-20px;">
<strong>
Not Accessible</strong>
<p class="muted">Your library or personal account may give you access</p>
</div>
</div>
<div class="col-md-10 pr-0 abstract-container">
<div class="abstract-tools-header">
<div class="article-tools d-lg-flex w-100">
<ul class="tool-list-one">
<li class="pdf-download"><a href="viewmedia.cfm?uri=ol-35-4-514&seq=0" target="_blank" aria-label="Pdf icon"><i class="fal fa-file-pdf"></i><span class="hidden-xs"><br>Get PDF</span></a></li>
<li><a href="mailto:?subject=Article Published in Optics Letters&body=I would like to notify you about the following article published in Optics Letters:%0AJaeduck Jang, Chae Yun Bae, Je-Kyun Park, and Jong Chul Ye, &quot;Self-reference quantitative phase microscopy for microfluidic devices,&quot; Opt. Lett. 35, 514-516 (2010)%0Ahttps://opg.optica.org/ol/abstract.cfm?URI=ol-35-4-514%0A---------------------------------------------------------------------------%0AThis is sent to you as an email notification feature from Optica Publishing Group: https://opg.optica.org" aria-label="Mail icon"><i class="fal fa-envelope"></i><span class="hidden-xs"><br>Email</span></a></li>
<li class="dropdown js-article-dropdown">
<button
class="dropdown-toggle js-article-dropdown-toggle border-0 bg-transparent"
aria-label="Open sharing options"
aria-haspopup="true"
aria-expanded="false"
aria-controls="share-menu"
>
<i class="fal fa-share-alt" aria-hidden="true"></i>
<span class="hidden-xs"><br>Share <span class="caret" aria-hidden="true"></span></span>
</button>
<ul class="dropdown-menu list-unstyled" role="menu">
<li role="none"><a role="menuitem" href="https://www.facebook.com/sharer.php?u=https%3A%2F%2Fopg%2Eoptica%2Eorg%2Fol%2Fabstract%2Ecfm%3Furi%3Dol%2D35%2D4%2D514" class="sharefacebook" target="_blank"><i class="fab fa-facebook-f mr-1" style="color: #ffffff;"></i>Share with Facebook</a></li>
<li role="none"><a role="menuitem" href="https://twitter.com/intent/tweet?text=Reading this OL article %23OSA_OL https%3A%2F%2Fopg%2Eoptica%2Eorg%2Fol%2Fabstract%2Ecfm%3Furi%3Dol%2D35%2D4%2D514" class="sharetwitter" target="_blank"><i class="icon-x mr-1" style="font-size: 24px;font-family: Arial, sans-serif; color:#ffffff;"><strong>X</strong></i>Share on X</a></li>
<li role="none"><a role="menuitem" href="https://www.reddit.com/submit?url=https%3A%2F%2Fopg%2Eoptica%2Eorg%2Fol%2Fabstract%2Ecfm%3Furi%3Dol%2D35%2D4%2D514" class="sharereddit" target="_blank"><i class="fab fa-reddit-alien mr-1" style="color: #ffffff;"></i>Post on reddit</a></li>
<li role="none"><a role="menuitem" href="https://www.linkedin.com/cws/share?url=https%3A%2F%2Fopg%2Eoptica%2Eorg%2Fservices%2Fopen%5Fmd%2Ecfm%3Furi%3Dol%2D35%2D4%2D514" class="sharelinkedin" target="_blank"><i class="fab fa-linkedin mr-1" style="color: #ffffff;"></i>Share with LinkedIn</a></li>
<li role="none"><a role="menuitem" href="http://www.mendeley.com/import/?url=https%3A%2F%2Fopg%2Eoptica%2Eorg%2Fol%2Fabstract%2Ecfm%3Furi%3Dol%2D35%2D4%2D514" class="sharemendeley" target="_blank"><i class="fab fa-mendeley mr-1" style="color: #ffffff;"></i>Add to Mendeley</a></li>
<li role="none"><a role="menuitem" href="https://www.bibsonomy.org/ShowBookmarkEntry?c=b&jump=yes&url=https%3A%2F%2Fopg%2Eoptica%2Eorg%2Fol%2Fabstract%2Ecfm%3Furi%3Dol%2D35%2D4%2D514" class="sharebibsonomy" target="_blank"><img src="/images/bibsonomy-icon.png" alt="Add to BibSonomy" title="BibSonomy" class="share-icon">Add to BibSonomy</a></li>
<li role="none"><a role="menuitem" href="https://www.addtoany.com/add_to/wechat?linkurl=https%3A%2F%2Fopg%2Eoptica%2Eorg%2Fol%2Fabstract%2Ecfm%3Furi%3Dol%2D35%2D4%2D514&linkname=ol-35-4-514" class="sharewechat" target="_blank"><i class="fab fa-weixin mr-1" style="color: #ffffff;"></i>Share with WeChat</a></li>
</ul>
</li>
<li class="get-citation dropdown js-article-dropdown">
<button
id="getCitation__toggle"
class="dropdown-toggle js-article-dropdown-toggle border-0 bg-transparent"
aria-label="Open citation options"
aria-haspopup="true"
aria-expanded="false"
aria-controls="share-menu"
>
<i class="fal fa-quote-right" aria-hidden="true"></i>
<span class="hidden-xs"><br>Get Citation <span class="caret" aria-hidden="true"></span></span>
</button>
<div id="getCitation" class="get-citation-content dropdown-menu">
<strong>Copy Citation Text</strong>
<div class="citation-text">
Jaeduck Jang, Chae Yun Bae, Je-Kyun Park, and Jong Chul Ye, "Self-reference quantitative phase microscopy for microfluidic devices," Opt. Lett. <b>35</b>, 514-516 (2010)
</div>
<form name="articlesForm" id="articlesForm" method="post" action="" style="display: inline">
<input type="hidden" name="articles" value="195503">
<input type="hidden" name="ArticleAction" value=""></form>
<strong>Export Citation</strong>
<ul class="list-unstyled">
<li><a href="#" data-action="export_bibtex" class="js-checkbox-actions">BibTex</a></li>
<li><a href="#" data-action="export_endnote" class="js-checkbox-actions">Endnote (RIS)</a></li>
<li><a href="#" data-action="export_html" class="js-checkbox-actions">HTML</a></li>
<li><a href="#" data-action="export_txt" class="js-checkbox-actions">Plain Text</a></li>
</ul>
</div>
</li>
<li><a href="#" data-bs-toggle="modal" data-bs-target="#userLogin" aria-label="Set citation alert"><i class="fal fa-engine-warning"></i><span class="hidden-xs"><br>Citation alert</span></a></li>
<li><a href="/user/favorites_add_article.cfm?articles=195503" target="_blank" aria-label="Save icon"><i class="fal fa-folder-upload"></i><span class="hidden-xs"><br>Save article</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
<a id="content" class="hidden"></a>
<div class="row">
<!-- Aux Sidebar -->
<div class="col-sm-3 col-sm-push-9 article-secondary">
<div class="sidebar-nav hidden-xs">
<ul class="right-nav">
<li class="sub-list">
<h3 class="osap-accordion__label right-nav__label">
<button class="btn p-0 text-start w-100 collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#relatedTopics" aria-expanded="false" aria-controls="relatedTopics" id="toggle-relatedTopics">
<strong>Related Topics</strong>
<i class="far osap-accordion__chevron" aria-hidden="true"></i>
</button>
</h3>
<div id="relatedTopics" class="collapse osap-accordion__content" role="region" aria-labelledby="toggle-relatedTopics" data-bs-parent=".right-nav">
<em>Table of Contents Category</em>
<ul class="list-unstyled">
<li>Microscopy</li>
</ul>
<br>
<div id="topicsHelp" class="get-citation dropdown">
<em>Optics &amp; Photonics Topics</em> <div class="advanced-search-popup advanced-search-popup--article"><a id="topicsHelp__toggle" class="topicsHelp__toggle" title="Help Link">?</a></div>
<div class="get-citation-content dropdown-menu">
<span class="small">The topics in this list come from the <a href="/thesaurus/default.cfm" target="_blank">Optics and Photonics Topics</a> applied to this article.</span>
</div>
</div>
<ul class="list-unstyled">
<li class="pb-1"><a class="js-relatedTopicLink" href="search.cfm?t=Materials|Microstructures|Microchannels">Microchannels</a></li>
<li class="pb-1"><a class="js-relatedTopicLink" href="search.cfm?t=Physical optics|Phase|Phase contrast">Phase contrast</a></li>
<li class="pb-1"><a class="js-relatedTopicLink" href="search.cfm?t=Measurement and metrology|Phase measurement">Phase measurement</a></li>
<li class="pb-1"><a class="js-relatedTopicLink" href="search.cfm?t=Physical optics|Phase|Phase noise">Phase noise</a></li>
<li class="pb-1"><a class="js-relatedTopicLink" href="search.cfm?t=Physical optics|Phase|Phase shift">Phase shift</a></li>
<li class="pb-1"><a class="js-relatedTopicLink" href="search.cfm?t=Optical devices|Optical modulators|Spatial light modulators">Spatial light modulators</a></li>
</ul>
<br>
</div>
</li>
</ul>
<ul class="right-nav">
<li class="sub-list">
<h3 class="osap-accordion__label right-nav__label">
<button class="btn p-0 text-start w-100" type="button" data-bs-toggle="collapse" data-bs-target="#aboutThisArticle" aria-expanded="true" aria-controls="aboutThisArticle" id="toggle-aboutArticle">
<strong>About this Article</strong>
<i class="far osap-accordion__chevron" aria-hidden="true"></i>
</button>
</h3>
<div id="aboutThisArticle" class="osap-accordion__content" role="region" aria-labelledby="toggle-aboutArticle" data-bs-parent=".right-nav">
<em>History</em>
<ul class="list-unstyled small">
<li>Original Manuscript: October 23, 2009</li>
<li>Revised Manuscript: December 17, 2009</li>
<li>Manuscript Accepted: January 11, 2010</li>
<li>Published: February 9, 2010</li>
</ul>
<br>
<em>Virtual Issues</em><br />
<a href="https://opg.optica.org/vjbo/virtual_issue.cfm?vid=103">Virtual Journal for Biomedical Optics Vol. 5, Iss. 5</a>
<br><br>
</div>
</li>
</ul>
</div>
<div id="referenceInfo" class="reference-info">
<!-- Dynamic Reference Info -->
</div>
</div>
<!-- Main Content -->
<div class="col-sm-9 col-sm-pull-3">
<div class="row">
<!-- Article Navigation -->
<div class="article-sidebar col-md-3">
<a style="color:white" href="viewmedia.cfm?uri=ol-35-4-514&seq=0" target="_blank" id="link-pdf"><button type="submit" class="btn btn-getpdf btn-sm" style="margin:2px 0px 1em 0px;width:100%;text-align:left;font-weight:600;">PDF Article</button></a>
<div id="articleNav" class="article-nav sub-page-nav">
<ul 
class="sidebar-nav-list"
data-action="change-section"
data-target="articleBody">
<li class="sidebar-nav-i">
<a href="#Abstract" class="sidebar-nav-link">Abstract</a>
</li>
<li class="sidebar-nav-i">
<a href="viewmedia.cfm?uri=ol-35-4-514&seq=0&html=true" class="sidebar-nav-link">Full Article</a>
</li>
</ul>
<ul class="sidebar-nav-list navextras">
<li class="sidebar-nav-i">
<a
id="figurestablink"
data-target="articleFigures"
href="#articleFigures"
class="sidebar-nav-link"
data-action="change-section">
Figures (<span class="sidebar-hlight">4</span>)
</a>
</li>
<li class="sidebar-nav-i">
<a href="#articleEquations"
class="sidebar-nav-link"
data-action="change-section"
data-target="articleEquations">
Equations (<span class="sidebar-hlight">2</span>)
</a>
</li>
<li class="sidebar-nav-i">
<a href="#articleReferences"
id="articleNavRefLink"
class="sidebar-nav-link"
data-action="change-section"
data-target="articleReferences"
data-article-id="195503">
References (<span class="sidebar-hlight">13</span>)
</a>
</li>
<li class="sidebar-nav-i">
<a href="#articleCitations"
id="articleNavCitationLink"
class="sidebar-nav-link"
data-article-id="195503"
data-action="change-section"
data-target="articleCitations">
Cited By <span id="numrefs">(<span class="sidebar-hlight">93</span>)</span>
</a>
</li>
<li class="sidebar-nav-i">
<a href="#articleMetrics"
id="articleNavMetricsLink"
class="sidebar-nav-link"
data-action="change-section"
data-target="articleMetrics"
data-article-id="195503">
Metrics
</a>
</li>
<li class="sidebar-nav-i"><a href="#top" class="sidebar-nav__top-link">Back to Top</a></li>
</ul>
</div>
</div>
<!-- Article Body -->
<div class="main-content col-md-9">
<div id="articleBody" class="article-section page-section active">
<h2 class="article-heading" id="Abstract">Abstract</h2>
<div lang="en">
<p><p xmlns:ali="http://www.niso.org/schemas/ali/1.0/" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">This Letter describes a quantitative phase microscopy for microfluidic devices using a simple self-referencing interferometry. Compared with the gross dimensions of the microfluidic device, the microchannel occupies only a small area of the device. Hence, the reference field can be generated by inverting the relative position of the specimen and background. Our system is realized using an extended depth-of-field optics in the form of Michelson interferometry, which allows quantitative phase measurement for an increased depth-of-field without moving objective lens or specimen. Furthermore, the system can be readily converted to a higher signal-to-noise ratio Hilbert phase microscopy thanks to the simultaneous acquisition of double interferograms. The performance of our system is verified using polymer beads, micropatterning poly(dimethylsiloxane) (PDMS), and embryo cells in the microchannels.</p></p>
</div>
<p>© 2010 Optical Society of America</p>
<a href="viewmedia.cfm?uri=ol-35-4-514&seq=0&html=true" id="link-full">Full Article</a>&nbsp; |&nbsp;
<a href="viewmedia.cfm?uri=ol-35-4-514&seq=0" target="_blank" id="link-pdf">PDF Article</a>
<hr style="margin-top:5em;">
<strong>More Like This</strong>
<div class="content-item media-twbs">
<div class="media-twbs-left">
<img class="media-object" src="/getThumbnail.cfm?uri=ol-35-20-3390&o=y" width="50" height="50" aria-hidden="true" role="presentation">
</div>
<div class="media-twbs-body">
<a class="js-relatedArticleLink" href="/ol/abstract.cfm?uri=ol-35-20-3390">Digital self-referencing quantitative phase microscopy by wavefront folding in holographic image reconstruction</a>
<p>G. Coppola, G. Di Caprio, M. Gioffré, R. Puglisi, D. Balduzzi, A. Galli, L. Miccio, M. Paturzo, S. Grilli, A. Finizio, and P. Ferraro<br>
<span class="muted">Opt. Lett. <strong>35</strong>(20) 3390-3392 (2010)</span></p>
</div>
</div>
<div class="content-item media-twbs">
<div class="media-twbs-left">
<img class="media-object" src="/getThumbnail.cfm?uri=ol-35-14-2370&o=y" width="50" height="50" aria-hidden="true" role="presentation">
</div>
<div class="media-twbs-body">
<a class="js-relatedArticleLink" href="/ol/abstract.cfm?uri=ol-35-14-2370">Quantitative DIC microscopy using an off-axis self-interference approach</a>
<p>Dan Fu, Seungeun Oh, Wonshik Choi, Toyohiko Yamauchi, August Dorn, Zahid Yaqoob, Ramachandra R. Dasari, and Michael S. Feld<br>
<span class="muted">Opt. Lett. <strong>35</strong>(14) 2370-2372 (2010)</span></p>
</div>
</div>
<div class="content-item media-twbs">
<div class="media-twbs-left">
<img class="media-object" src="/getThumbnail.cfm?uri=ol-35-15-2612&o=y" width="50" height="50" aria-hidden="true" role="presentation">
</div>
<div class="media-twbs-body">
<a class="js-relatedArticleLink" href="/ol/abstract.cfm?uri=ol-35-15-2612">Simultaneous two-wavelength transmission quantitative phase microscopy with a color camera</a>
<p>Matthew T. Rinehart, Natan T. Shaked, Nathan J. Jenness, Robert L. Clark, and Adam Wax<br>
<span class="muted">Opt. Lett. <strong>35</strong>(15) 2612-2614 (2010)</span></p>
</div>
</div>
<div class="content-item media-twbs-body relatedmorelink" style="text-align:center">
<a href="#">View More...</a>
</div>
<div class="relatedmore" style="display:none">
<div class="content-item media-twbs">
<div class="media-twbs-left">
<img class="media-object" src="/getThumbnail.cfm?uri=ao-55-3-A54&o=y" width="50" height="50" aria-hidden="true" role="presentation">
</div>
<div class="media-twbs-body">
<a class="js-relatedArticleLink" href="/ao/abstract.cfm?uri=ao-55-3-A54">Optofluidic bioimaging platform for quantitative phase imaging of lab on a chip devices using digital holographic microscopy</a>
<p>Vimal Prabhu Pandiyan and Renu John<br>
<span class="muted">Appl. Opt. <strong>55</strong>(3) A54-A59 (2016)</span></p>
</div>
</div>
<div class="content-item media-twbs">
<div class="media-twbs-left">
<img class="media-object" src="/getThumbnail.cfm?uri=oe-29-15-24210&o=y" width="50" height="50" aria-hidden="true" role="presentation">
</div>
<div class="media-twbs-body">
<a class="js-relatedArticleLink" href="/oe/abstract.cfm?uri=oe-29-15-24210">Single-plane and multiplane quantitative phase imaging by self-reference on-axis holography with a phase-shifting method</a>
<p>Nathaniel Hai and Joseph Rosen<br>
<span class="muted">Opt. Express <strong>29</strong>(15) 24210-24225 (2021)</span></p>
</div>
</div>
</div>
<div style="width:100%; padding: 40px 0px 0px 0px;">
<a href="abstract.cfm?uri=ol-35-4-511" class="ft-article-prev"><i class="fal fa-caret-left"></i> Previous Article</a>
<a href="abstract.cfm?uri=ol-35-4-517" class="ft-article-next">Next Article <i class="fal fa-caret-right"></i></a>
</div>
</div>
<div id="articleReferences" class="article-section page-section small">
<div id="refsList"></div>
</div>
<div id="articleCitations" class="article-section page-section small">
<h3 class="article-heading">Cited By</h3>
<p>You do not have subscription access to this journal. Cited by links are available to subscribers only. You may subscribe either as an Optica member, or as an authorized user of your institution.
<p>Contact your librarian or system administrator
<br>or<br>
<a href="#" data-bs-toggle="modal" data-bs-target="#userLogin">Login to access Optica Member Subscription</a>
</p>
</div>
<div id="articleFigures" class="article-section page-section media-section ">
<h3 class="article-heading">Figures (4)</h3>
<p>You do not have subscription access to this journal. Figure files are available to subscribers only. You may subscribe either as an Optica member, or as an authorized user of your institution.
<p>Contact your librarian or system administrator
<br>or<br>
<a href="#" data-bs-toggle="modal" data-bs-target="#userLogin">Login to access Optica Member Subscription</a>
</p>
</div>
<div id="articleEquations" class="article-section page-section small">
<h3 class="article-heading">Equations (2)</h3>
<p>You do not have subscription access to this journal. Equations are available to subscribers only. You may subscribe either as an Optica member, or as an authorized user of your institution.
<p>Contact your librarian or system administrator
<br>or<br>
<a href="#" data-bs-toggle="modal" data-bs-target="#userLogin">Login to access Optica Member Subscription</a>
</p>
</div>
<div id="articleMetrics" class="article-section page-section small">
<div id="metricsData"></div>
</div>
</div>
</div>
</div>
</div>
<div class="hidden-sm hidden-md hidden-lg secondary-navigation--footer">
<div style="padding: 5px 0px 0px 0px;">
<div class="journal-nav-item hidden-md hidden-lg hidden-sm">
<div class="mobile-journal-header p-0">
<a href="/ol/home.cfm"><h1>Optics Letters</h1>
<p class="primary-editors">Carsten Rockstuhl, Editor-in-Chief</p></a>
</div>
</div>
<div class="journal-nav-item hidden-xs ">
<a class="secondary-nav-item_link" href="/ol/home.cfm" >Journal Home</a>
</div>
<div class="journal-nav-item ">
<a class="secondary-nav-item_link" href="/content/journal/about/item/ol/" >About</a>
</div>
<div class="journal-nav-item ">
<a class="secondary-nav-item_link" href="/ol/upcomingissue.cfm" >Issues in Progress</a>
</div>
<div class="journal-nav-item ">
<a class="secondary-nav-item_link" href="/ol/issue.cfm" >Current Issue</a>
</div>
<div class="journal-nav-item ">
<a class="secondary-nav-item_link" href="/ol/browse.cfm" >All Issues</a>
</div>
<div class="journal-nav-item ">
<a class="secondary-nav-item_link" href="/ol/upcoming.cfm" >Early Posting</a>
</div>
</div>
</div>
</div>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/Javascript">
function alertconfirmed() {
// Send ajax to confirm
document.getElementById('confirmAlertButton').disabled = 'disabled';
$.ajax({
cache: false,
type: "GET",
url: "set_citation_alert.cfm?uri=ol-35-4-514&confirmalert=true"
}).done(function( ajxretmsg ) {
if (ajxretmsg == "1") {
document.getElementById('alertConfirmArea').innerHTML = '<strong>Your alert has been set!</strong><br><br><input type="button" name="closeEmail" data-bs-dismiss="modal" value="Close">';
} else {
document.getElementById('alertConfirmArea').innerHTML = 'There was an error setting your alert. Please try again later.<br><br><input type="button" name="closeEmail" data-bs-dismiss="modal" value="Close">';
}
});
}
const alertButton = document.getElementById('confirmAlertButton');
if (alertButton) {
alertButton.addEventListener('click', alertconfirmed);
}
</script>
<div class="modal fade" id="setCitationModal" tabindex="-1" role="dialog" aria-labelledby="setCitationLabel" aria-hidden="true">
<div class="modal-dialog login-dialog">
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-bs-dismiss="modal" aria-hidden="true">&times;</button>
<h4 class="modal-title" id="setCitationLabel">Confirm Citation Alert</h4>
</div>
<div class="modal-body">
Please <a data-bs-toggle="modal" data-bs-target="#userLogin">login</a> to set citation alerts.
</div>
</div>
</div>
</div>
<div class="modal fade" id="mathJaxHelp" tabindex="-1" role="dialog" aria-labelledby="mathJaxHelp" aria-hidden="true">
<div class="modal-dialog login-dialog">
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-bs-dismiss="modal" aria-hidden="true">&times;</button>
MathJax Help
</div>
<div class="modal-body">
Equations displayed with <a href="http://www.mathjax.org" target="_blank">MathJax</a>. Right click equation to reveal menu options.
</div>
</div>
</div>
</div>
</div></div></div></div>
<div id="formErrors" class="modal fade" role="dialog">
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<button class="close" data-dismiss="modal" aria-label="close">
<span aria-hidden="true">&times;</span>
</button>
<h4 class="modal-title">Field Error</h4>
</div>
<div class="modal-body">
<p id="formErrorsText"></p>
</div>
<div class="modal-footer">
<button class="btn btn-primary" data-dismiss="modal">Ok</button>
</div>
</div>
</div>
</div>
<div id="avsModal" class="avs-modal">
<div id="avsModalContent" class="avs-modal-content">
<strong>Select <span id="titleFiltersPopup"></span> as filters</strong>
<hr>
<div class="row">
<div class="col-md-8">
<div class="input-collapse">
<input id="input-popup-selectize" type="text" class="form-control selectized" placeholder="(type names or look up list)" tabindex="-1" aria-label="type names or look up list"/>
<div class="selectize-control form-control multi"></div>
</div>
</div>
</div>
<hr>
<ul id="checkBoxList"></ul>
<hr>
<span id="avsModalSubmit" class="btn btn-primary">Select Topics</span> <span id="avsModalClose" class="cancel"> Cancel</span>
</div>
</div>
<footer><div class="container ft-links"><a id="global-nav"></a>
<nav aria-label="Back to top"><div class="top-button"><a href="#" style="color:white;"><span class="fi-arrow-up"> Top </span></a></div></nav>
<div class="col-sm-3">
<ul class="ft-links-list">
<li><a href="/">Publishing Home</a></li>
<li><a href="/about.cfm">Journals</a></li>
<li><a href="/conferences.cfm">Conferences</a></li>
<li><a target="_blank" href="https://opticapreprints.figshare.com/">Preprints (Optica Open) <span class="fal fa-external-link"></span></a></li>
</ul>
<ul class="ft-links-list">
<li class="ft-links-header">Information for</li>
<li><a href="/content/author/">Authors</a></li>
<li><a href="/content/reviewer/">Reviewers</a></li>
<li><a href="/content/library/">Librarians</a></li>
</ul>
</div>
<div class="col-sm-3">
<ul class="ft-links-list">
<li class="ft-links-header">Open Access Information</li>
<li><a href="/content/author/portal/item/review-open-access-policy-stat/">Open Access Statement and Policy</a></li>
<li><a href="/library/license_v2.cfm">Terms for Journal Article Reuse</a></li>
</ul>
<ul class="ft-links-list">
<li class="ft-links-header">Other Resources</li>
<li><a target="_blank" href="https://opticapreprints.figshare.com/" >Optica Open <span class="fal fa-external-link"></span></a></li>	
<li><a href="/content/bookshelf/">Optica Publishing Group Bookshelf</a></li>
<li><a href="/info/opticsimagebank.cfm">Optics ImageBank</a></li>
<li><a href="https://www.optica-opn.org/home/" target="_blank">Optics &amp; Photonics News <span class="fal fa-external-link"></span></a></li>
<li><a href="/spotlight/">Spotlight on Optics</a></li>
<li><a href="https://www.optica.org">Optica Home</a></li>
</ul>
<!-- mobile only regional sites link -->
</div>
<div class="col-sm-3">
<ul class="ft-links-list">
<li class="ft-links-header">Accessibility Information</li>
<li><a href="/content/library/portal/item/accessibility-statement">OPG Accessibility Statement</a></li>	
</ul>
<ul class="ft-links-list">
<li class="ft-links-header">About</li>
<!--"INDUSTRY REPORTS" LINK TEMPORARILY DISABLED ON 3/3/2023 UNTIL FURTHER NOTICE FROM CORP DEPT.-->
<!--li><a href="/industryreports.cfm">Industry Reports</a></li-->
<li><a href="/about.cfm">About Optica Publishing Group</a></li>
<li><a href="/content/info/portal/item/benefitslog">About My Account</a></li>
<li><a href="/user/toc_alerts_subscribe.cfm">Sign up for Alerts</a></li>
<li><a href="/content/info/portal/item/contactus/">Contact Us</a></li>
<li><a href="/submitFeedback.cfm?url=" target="SingleOpgWindow">Send Us Feedback</a></li>
</ul>
</div>
<div class="col-sm-3">
<ul class="nav navbar-nav navbar-right navbar-ft hidden-sm hidden-xs d-flex flex-row">
<li class="dropdown" style="border:1px solid #6c6c6c; margin-right: 10px;">
<a href="#" class="dropdown-toggle navbar-ft-header" data-bs-toggle="dropdown">My Favorites <strong class="caret"></strong></a>
<ul class="dropdown-menu up">
<li><a href="/user">Go to My Account</a></li>
<li><a href="#" data-bs-toggle="modal" data-bs-target="#userLogin">Login to access favorites</a></li>
</ul>
</li>
<li class="dropdown" style="border:1px solid #6c6c6c;">
<a href="#" class="dropdown-toggle navbar-ft-header" data-bs-toggle="dropdown">Recent Pages <strong class="caret"></strong></a>
<ul class="dropdown-menu up recent-page-list">
</ul>
</li>
</ul>
</div>
<div>
<div class="col-xs-12 col-md-3 col-md-offset-9 text-right" style="margin-top:-40px;">
<a class="ft-links-header purple-hover" href="https://www.twitter.com/OpticaPubsGroup" target="_blank" aria-label="Follow @OpticaPubsGroup on Twitter">
<span class="fa-2x fa-square-x-twitter me-2">X</span>
</a>
<a class="ft-links-header purple-hover" href="https://www.facebook.com/OpticaWorldwide" target="_blank" aria-label="Follow us on Facebook">
<span class="fab fa-2x fa-facebook-square">&nbsp;</span>
</a>
<a class="ft-links-header purple-hover" href="https://www.linkedin.com/company/optica-worldwide/" target="_blank" aria-label="Follow us on LinkedIn">
<span class="fab fa-2x fa-linkedin">&nbsp;</span>
</a>
<a class="ft-links-header purple-hover" href="/toc_alerts_subscribe.cfm" target="_blank" aria-label="RSS Alerts">
<span class="fas fa-2x fa-rss-square">&nbsp;</span>
</a>
</div>
</div></div>
<div class="ft-bottom">
<div class="container">
<div class="col-sm-10">
&copy; Copyright 2026 | Optica Publishing Group. All rights reserved, including rights for text and data mining and training of artificial technologies or similar technologies.
</div>
<div class="col-sm-2 ft-right">
<a class="footer-link" href="/content/info/portal/item/privacy">Privacy</a> | <a class="footer-link" href="/content/info/portal/item/termsofuse">Terms of Use</a>
</div>
</div>
</div></footer>
<div class="modal fade" id="userLogin" aria-hidden="true" role="dialog">
<div class="modal-dialog login-dialog">
<div class="modal-content">
<div class="modal-header flex-row-reverse">
<button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">&times;</button>
<h4 class="modal-title">Login or Create Account</h4>
</div>
<div class="modal-body">
<div class="mb-2 d-flex flex-row">
<div class="p-1">Sign in by:</div>
<ul class="nav nav-pills" id="loginTabs" role="tablist">
<li class="nav-item" role="presentation">
<button type="button" class="nav-link active" id="login-tab" data-bs-toggle="tab" data-bs-target="#login" role="tab" aria-controls="login" aria-selected="true">Login</button>
</li>
<li class="nav-item" role="presentation">
<button type="button" class="nav-link" id="loginbyemail-tab" data-bs-toggle="tab" data-bs-target="#loginbyemail" role="tab" aria-controls="loginbyemail" aria-selected="false">Login by Email</button>
</li>
</ul>
</div>
<div class="alert alert-danger loginErr" role="alert" aria-live="assertive" style="display:none;"></div>
<div class="alert alert-warning loginLoading" style="display:none;">Please wait...</div>
<div class="alert alert-info mailInfo" id="mailMessage" style="display:none;"></div>
<div class="tab-content">
<div role="tabpanel" class="tab-pane active" id="login" aria-labelledby="login-tab">
<form class="form-horizontal needs-validation" role="form" id="loginForm">
<div class="mb-3">
<label for="inputEmail" class="form-label">Email*</label>
<input type="email" class="form-control js-inline-validate" id="inputEmail" placeholder="Email" required autofocus>
</div>
<div class="mb-3">
<label for="inputPassword" class="form-label">Password*</label>
<input type="password" class="form-control js-inline-validate" id="inputPassword" placeholder="Password" required>
<span class="help-block"><a href="https://account.optica.org/eweb/Dynamicpage.aspx?webcode=forgotpassword&Site=osac">Forgot your password?</a></span>
</div>
<div class="form-check">
<input type="checkbox" class="form-check-input" id="rememberme">
<label class="form-check-label" for="rememberme">Remember me on this computer</label>
</div>
<div class="mb-3">
<button type="submit" class="btn btn-primary" id="loginButton">Login</button>
<button class="btn btn-default" data-bs-dismiss="modal" data-bs-target="#userLogin">Cancel</button>
</div>
</form>
</div>
<div role="tabpanel" class="tab-pane" id="loginbyemail" aria-labelledby="loginbyemail-tab">
<form class="form needs-validation" id="loginByEmailForm" role="form">
<div class="mb-3">
<p>We need to verify your email address to ensure your account’s security.</p>
<p>Enter the primary email address associated with your Optica account, then click the button below to receive an email with a link to log in.</p>
<p>If you don’t receive the email, check your Spam folder.</p>
</div>
<div class="mb-3">
<label for="inputLoginByEmail" class="form-label">Email</label>
<input
type="email"
id="inputLoginByEmail"
class="form-control js-inline-validate"
required
autofocus
placeholder="your@email.here"
/>
</div>
<div class="mb-3">
<button type="submit" class="btn btn-primary" id="loginByEmailSubmit">Send Validation Email</button>
<button class="btn btn-default" data-bs-dismiss="modal" data-bs-target="#userLogin">Cancel</button>
</div>
</form>
</div>
</div>
<p>Don't have an account? <a href="/util/create-account.cfm">Create an Account.</a></p>
</div>
<div class="modal-footer">
<div class="col-xs-12" style="text-align: left"><a href="https://auth.optica.org/connect/authorize?client_id=osap&response_type=id_token token&scope=openid email profile affiliation&redirect_uri=https%3A%2F%2Fopg%2Eoptica%2Eorg%2Fdefault%2Ecfm&state=A8BF0ED7-C837-467B-8B70043B61897E6D|https%3A%2F%2Fopg%2Eoptica%2Eorg%2Fabstract%2Ecfm%3Frwjcode%3Dol%26uri%3Dol%2D35%2D4%2D514&nonce=A8BF0ED7-C837-467B-8B70043B61897E6D&acr_values=idp:oa&response_mode=form_post">Institutional Login</a> (Optica Publishing Group participates in eduGAIN)</div>
</div>
<div class="modal-footer">
<div class="col-xs-12" style="text-align: left"><a href="https://auth.optica.org/connect/authorize?client_id=osap&response_type=id_token token&scope=openid email profile affiliation&redirect_uri=https%3A%2F%2Fopg%2Eoptica%2Eorg%2Fdefault%2Ecfm&state=A8BF0ED7-C837-467B-8B70043B61897E6D|https%3A%2F%2Fopg%2Eoptica%2Eorg%2Fabstract%2Ecfm%3Frwjcode%3Dol%26uri%3Dol%2D35%2D4%2D514&nonce=A8BF0ED7-C837-467B-8B70043B61897E6D&acr_values=idp:oa&response_mode=form_post">China CARSI Member Access</a></div>
</div>
<div class="modal-footer">
<div class="col-xs-12" style="text-align: left"><a href="/openathens.cfm?entity=https%3A%2F%2Fpassport.escience.cn%2Fidp%2Fshibboleth">China CAoS Member Access</a></div>
</div>
<div class="modal-footer flex-nowrap">
<div class="col-xs-6" style="text-align: left"><a href="/content/info/portal/item/privacy">Privacy Policy</a></div>
<div class="col-xs-6"><a href="https://www.optica.org/help/">Need help?</a> <i class="fal fa-info-circle"></i></div>
</div>
</div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
</div>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=">
window.MathJax = {
chtml: {
mathmlSpacing: true,
mtextInheritFont: true,
displayAlign: 'center',
scale: 1,
},
svg: {
mtextInheritFont: true,
},
options: {
menuOptions: {
settings: {
zoom: 'Click',
zscale: '200%',
},
},
ignoreHtmlClass: 'tex2jax_ignore',
processHtmlClass: 'tex2jax_process',
},
mml: {
parseError: (node) => {
console.log('MathML Parse Error handled');
},
},
tex: {
inlineMath: [
['$', '$'],
['\\(', '\\)'],
],
processEscapes: true,
macros: {
bm: ['\\mathbf{#1}', 1],
scalebox: ['{ }', 1],
resizebox: ['{ }', 1],
vskip: ['{ }', 1],
noalign: ['{ }', 1],
dag: '\\dagger',
upalpha: '\\text{α}',
upbeta: '\\text{β}',
upgamma: '\\text{γ}',
updelta: '\\text{δ}',
upepsilon: '\\text{ε}',
upzeta: '\\text{ζ}',
upeta: '\\text{η}',
uptheta: '\\text{θ}',
upiota: '\\text{ι}',
upkappa: '\\text{κ}',
uplambda: '\\text{λ}',
upmu: '\\text{μ}',
upnu: '\\text{ν}',
upxi: '\\text{ξ}',
upomicron: '\\text{ο}',
uppi: '\\text{π}',
uprho: '\\text{ρ}',
upsigma: '\\text{σ}',
uptau: '\\text{τ}',
upupsilon: '\\text{υ}',
upphi: '\\text{φ}',
upchi: '\\text{χ}',
uppsi: '\\text{ψ}',
upomega: '\\text{ω}',
upGamma: '\\text{Γ}',
upDelta: '\\text{Δ}',
upTheta: '\\text{Θ}',
upLambda: '\\text{Λ}',
upXi: '\\text{Ξ}',
upPi: '\\text{Π}',
upSigma: '\\text{Σ}',
upUpsilon: '\\text{Υ}',
upPhi: '\\text{Φ}',
upPsi: '\\text{Ψ}',
upOmega: '\\text{Ω}',
upvarepsilon: '\\text{ϵ}',
upvartheta: '\\text{ϑ}',
upvarrho: '\\text{ϱ}',
upvarpi: '\\text{φ}',
},
packages: {
'[+]': [
'action',
'ams',
'amscd',
'bbox',
'boldsymbol',
'braket',
'bussproofs',
'cancel',
'cases',
'centernot',
'color',
'colorv2',
'configmacros',
'empheq',
'enclose',
'extpfeil',
'gensymb',
'html',
'mathtools',
'mhchem',
'newcommand',
'noerrors',
'noundefined',
'physics',
'setoptions',
'tagformat',
'textcomp',
'textmacros',
'unicode',
'units',
'upgreek',
'verb',
],
},
},
loader: {
load: [
'[tex]/action',
'[tex]/ams',
'[tex]/amscd',
'[tex]/bbox',
'[tex]/boldsymbol',
'[tex]/braket',
'[tex]/bussproofs',
'[tex]/cancel',
'[tex]/cases',
'[tex]/centernot',
'[tex]/color',
'[tex]/colorv2',
'[tex]/configmacros',
'[tex]/empheq',
'[tex]/enclose',
'[tex]/extpfeil',
'[tex]/gensymb',
'[tex]/html',
'[tex]/mathtools',
'[tex]/mhchem',
'[tex]/newcommand',
'[tex]/noerrors',
'[tex]/noundefined',
'[tex]/physics',
'[tex]/setoptions',
'[tex]/tagformat',
'[tex]/textcomp',
'[tex]/textmacros',
'[tex]/unicode',
'[tex]/units',
'[tex]/upgreek',
'[tex]/verb',
],
},
};
</script>
<script defer nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" src="https://cdn.jsdelivr.net/npm/mathjax@4.1.1/tex-mml-svg.js" id="MathJax-script"></script>
<!-- <script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=">
document.write('<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" src=' +
('__proto__' in {} ? 'js/vendor/zepto' : 'js/vendor/jquery') +
'.js><\/script>')
</script> -->
<!--these are the concatenated scripts - when we're done with the JS, we should put together a cfif to serve these if it's not on development-->
<!--
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" src="/js/libraries.min.js" type="text/javascript"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" src="/js/app.min.js" type="text/javascript"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" src="/js/full-search.min.js" type="text/javascript"></script>
-->
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" src="/js/vendor/jquery.autocomplete.min.js"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" src="/js/vendor/selectize.js?v=11102021"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" src="/js/vendor/selectize.custom.js"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" src="/js/vendor/sly.min.js"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" src="/js/jquery.tinysort.min.js"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" src="/js/app.js?v=05292026v3"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" src="/js/recentPages.js?v=11102021"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/purify.min.js"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" src="/js/quickpager.jquery.js"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" src="/js/jquery.unveil.js"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/jquery.tokeninput.js"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/jquery.base64.js"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" src="/js/search.js?v=12202024"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/underscore.js"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" src="https://code.jquery.com/ui/1.13.2/jquery-ui.js" integrity="sha256-xLD7nhI62fcsEZK2/v8LsBcb4lG7dgULkuXoXB/j91c=" crossorigin="anonymous"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/search/ApiClient.js?v=02082023"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/search/Bus.js?v=02082023"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/search/Config.js?v=02082023"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/search/Constants.js?v=02082023"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/search/Template.js?v=02082023"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/search/Facet.js?v=02082023"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/search/Pagination.js?v=02082023"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/search/Results.js?v=02082023"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/search/Search.js?v=12202024"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/search/Topics.js?v=07242023"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/search/Util.js?v=02082023"></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript" src="/js/search/Main.js?v=02082023"></script>
<!-- templates -->
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="template-page-size-selector">
<%= selected %>
<ul class="dropdown-menu">
<%= unselected %>
</ul>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="template-pagination-selected-page-size">
<a class="page_size_<%= size %> btn btn-default dropdown-toggle" data-bs-toggle="dropdown" href="#">
<%= size %>
<span class="caret"></span>
</a>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="template-pagination-unselected-page-size">
<li><a class="page_size_<%= size %>" href="#"><%= size %></a></li>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-row">
<li class="sr-item">
<input type="checkbox" class="sri-select hidden-xs" name="articles" value="<%= documentUri %>" aria-label="<%= documentUri %> checkbox"/>
<div class="sri-summary">
<p class="sri-title"><a href="<%= path %>abstract.cfm?uri=<%= documentUri %>&origin=search" target="_blank"><%= title %><%= videoIcon %></a></p>
<span class="sri-authors"><%= authors %></span>
<ul class="sri-details">
<li class="sri-year"><%= year %></li>
<li class="sri-journal"><%= access%> <%= name %><strong>&nbsp; View: <%= htmlLinks %><%= pdfLinks %></strong><%= xinfo %></li>
</ul>
<div class="sri-toggle-extended fi-plus">
</div>
</div>
<div class="sri-extended">
<div class="d-flex">
<img src="<%= imgLink%>" class="sri-image" height="100" width="100" alt="" loading="lazy" style="max-width: 150px; height: auto;" data-remove-on-error="true" />
<div>
<p class="sri-abstract"><%= abstract %></p>
<ul class="sri-hits list-unstyled">
<%= searchHits %>
</ul>
</div>
</div>
</div>
</li>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-image-result-row">
<li class="sr-item sr-item-image">
<div class="sri-summary">
<h3 class="sri-title">
<a href="<%= path %>" target="_blank">
<%= title %>
</a>
</h3>
<span class="sri-authors"><%= authors %></span>
<ul class="sri-details">
<li class="sri-year"><%= year %></li>
<li class="sri-journal"><%= access %> <%= journalTitle %> <strong><%= volume %></strong>(<%= issue %>) <%=firstPage %>&nbsp; <strong>View:</strong> <a href="<%= path %>" target="_blank">Image</a></li>
</ul>
</div>
<div class="sri-image-details">
<img src="<%= imgLink%>" class="sri-image" height="100" width="100" alt="<%=title%> thumbnail" loading="lazy" style="max-width: 150px; height: auto;"/>
<p class="sri-abstract">
<strong>Caption:</strong>&nbsp;<%= figLabel %><%= caption %></p>
</div>
</li>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-hit">
<li>&hellip;<%= hitText %>&hellip;</li>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-snippet-highlighted"><strong><%= text %></strong></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-snippet-xinfo"> [<%= xinfo %>]</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-snippet-pdf"><a href="<%= pdfUri %>" target="_blank">PDF</a></script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-snippet-html"><a href="<%= htmlUri %>" target="_blank">HTML</a> | </script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-element-visible">display:inline</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-element-hidden">display:none</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-element-nbsp">&nbsp;</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-facet">
<h5 class="bg1">
<span class="float_l">
<input type="checkbox" name="chkAllFacet-<%= name %>">
<%= facetName %>
</input>
</span>
<%= moreLink %>
<a id="sortby-<%= name %>" class="sidebar_more white" href="#">Sort</a>
</h5>
<ul id="facet-values-<%= name %>">
<%= facetValues %>
</ul>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="facet-publications">
<ul class="sf-list">
<li class="sf-list_list-item"><input id="publicationsAll" class="sf-select-all sf-list_input" type="checkbox" checked="checked" disabled="disabled"/> <label class="sf-list_label" for="publicationsAll">All</label></li>
<li class="sf-list_list-item"><input id="facet-publications-journals" class="sf-list_input" type="checkbox" name="publications"/> <label class="sf-list_label" for="facet-publications-journals">Journals <span class="facet-count">(<%= totalJournals %>)</span></label></li>
<li class="sf-list_list-item"><input id="facet-publications-proceedings" class="sf-list_input" type="checkbox" name="proceedings"/> <label class="sf-list_label" for="facet-publications-proceedings">Conferences <span class="facet-count">(<%= totalProceedings %>)</span></label></li>
<li class="sf-list_list-item d-none"><input id="facet-publications-reports" class="sf-list_input" type="checkbox" name="reports"/> <label class="sf-list_label" for="facet-publications-reports">Industry Reports <span class="facet-count">(<%= totalReports %>)</span></label></li>
</ul>
</div>
<div class="sf-module sf-journals">
<div class="row2">
<p id="facet-journal-show" class="sf-group-title collapsed" style="text-transform: none !important;">Journals</p>
<div id="sortJournal" class="sf-sort"></div>
</div>
<div id="facet-journal-values">
</div>
</div>
<div class="sf-module sf-proceedings">
<div class="row2">
<p id="facet-proceeding-show" class="sf-group-title collapsed" style="text-transform: none !important;">Conferences</p>
<div id="sortProceeding" class="sf-sort"></div>
</div>
<div id="facet-proceeding-values"></div>
</div>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-facet-basics">
<ul class="sf-list">
<li class="sf-select-all"><input id="<%= allId %>" type="checkbox" checked="checked" disabled="disabled"/> <label for="<%= allId %>">All</label></li>
<%= values %>
<li class="sf-expanded">
<a href="#" id="more-<%= allId %>" class="search-panel_more-link" data-bs-toggle="modal" data-bs-target="#modal-<%= allId %>">more <%=name%> &raquo;</a>
<div class="modal full fade" id="modal-<%= allId %>">
<div class="modal-dialog">
<div class="modal-content search">
<div class="row mbottom-20">
<div class="col-md-4">
<h3 class="modal-header search"><%= modalTitle %></h3>
</div>
<div class="col-md-6 col-md-offset-2">
<input id="input-<%= allId%>" type="text" class="form-control selectized" placeholder="(type names or look up list)" tabindex="-1" aria-label="type names or look up list"></input>
<div class="selectize-control form-control multi"></div>
</div>
</div>
<div class="modal_option-container mbottom-20 scrollable" id="moreUl-<%=allId%>">
</div>
<hr>
<div class="d-flex">
<a href="#" id="apply-<%= allId %>" class="btn btn-primary mr-1" data-bs-dismiss="modal">Apply Filters</a>
<a href="#" id="cancel-<%= allId %>" class="btn btn-default" data-bs-dismiss="modal">Cancel</a>
</div>
</div>
</div>
</div>
</li>
</ul>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-facet-terms">
<ul class="sf-list">
<li class="sf-select-all">
<input id="<%= allId %>" type="checkbox" checked="checked" disabled="disabled"/>
<label for="<%= allId %>">Remove all topic filters</label>
</li>
<%= values %>
<li class="sf-expanded">
<a href="#" id="more-<%= allId %>" class="search-panel_more-link hidden-xs" data-bs-toggle="modal" data-bs-target="#modal-<%= allId %>">include more topics &raquo;</a>
<div class="modal full fade" id="modal-<%= allId %>">
<div class="modal-dialog">
<div class="modal-content search">
<div class="row mbottom-20">
<div class="col-md-4">
<h3 class="modal-header search">Optics &amp; Photonics Topics</h3>
</div>
<div class="col-md-6 col-md-offset-2">
<input id="input-<%= allId%>" type="text" class="form-control" placeholder="Search for a specific topic" tabindex="-1" aria-label="Search for a specific topic"></input>
</div>
</div>
<div class="row mbottom-20">
<div class="col-md-12">
<strong>Browse the topics:</strong>
Click the <svg class="selection-list_arrow"><use xlink:href="#right-arrow" /></svg> to reveal subtopics. Use the checkbox to select a topic to filter your search.
</div>
</div>
<div class="modal_option-container mbottom-20 scrollable" id="moreUl-<%=allId%>">
</div>
<div class="row">
<div class="col-md-12">
<strong>Selected Topics</strong>
</div>
</div>
<div id="moreSelectedList"></div>
<div class="row"><div class="col-md-12">&nbsp;<!-- spacing row --></div></div>
<div class="d-flex">
<a href="#" id="apply-<%= allId %>" class="btn btn-primary mr-1" data-bs-dismiss="modal">Add Selected Topic Filters</a>
<a href="#" id="cancel-<%= allId %>" class="btn btn-default" data-bs-dismiss="modal">Cancel</a>
</div>
</div>
</div>
</div>
</li>
</ul>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-facet-journal-proceedings">
<ul class="sf-list">
<li class="sf-select-all"><input id="<%= allId %>" type="checkbox" checked> <label for="<%= allId %>">All</label></li>
<%= values %>
<li class="sf-expanded">
<a href="#" id="more-<%= allId %>" class="search-panel_more-link" data-bs-toggle="modal" data-bs-target="#modal-<%= allId %>" class="sf-expanded-toggle">more <%=name%> &raquo;</a>
<div class="modal full fade" id="modal-<%= allId %>">
<div class="modal-dialog">
<div class="modal-content search">
<div class="row mbottom-20">
<div class="col-md-4">
<h3 class="modal-header search"><%= modalTitle%></h3>
</div>
<div class="col-md-6 col-md-offset-2">
<input id="input-<%= allId%>" type="text" class="form-control selectized" placeholder="(type names or look up list)" tabindex="-1" aria-label="type names or look up list"></input>
<div class="selectize-control form-control multi"></div>
</div>
</div>
<div class="modal_option-container mbottom-20 scrollable" id="moreUl-<%=allId%>">
</div>
<hr>
<div class="d-flex">
<a href="#" id="apply-<%= allId %>" class="btn btn-primary mr-1" data-bs-dismiss="modal">Apply Filters</a>
<a href="#" id="cancel-<%= allId %>" class="btn btn-default" data-bs-dismiss="modal">Cancel</a>
</div>
</div>
</div>
</div>
</li>
</ul>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-facet-content">
<ul class="sf-list">
<%= values %>
</ul>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="facet-more-new-content">
<div class="more-columns_container">
<div class="more-columns_column"><ul class="selection-list"><%= val1%></ul></div>
<div class="more-columns_column"><ul class="selection-list"><%= val2%></ul></div>
<div class="more-columns_column"><ul class="selection-list"><%= val3%></ul></div>
</div>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="facet-more-terms-div">
<div class="more-columns_container">
<div class="more-columns_column" id="<%= name%>-col1"><%= val%></div>
<div class="more-columns_column" id="<%= name%>-col2"></div>
<div class="more-columns_column" id="<%= name%>-col3"></div>
</div>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="facet-more-terms-list">
<ul class="selection-list"><%= val%></ul>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-facet-more">
<a id="more-<%= name %>" href="#" class="sidebar_more white">More</a>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-facet-detail">
<a href="#" id="details-link-<%= id %>" class="sidebar_more black">details</a>
<ul id="details-container-<%= id %>" class="list-unstyled" style="display:none;" data-value="<%= valName %>"></ul>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-facet-value">
<li class="sf-list_list-item <%= rowclass %>" style="<%= display %>">
<input type="checkbox" class="sf-list_input visually-hidden" name="chkFacet-<%= name %>" value="<%= code %>" aria-label="<%= dataValue %>" data-value="<%= dataValue %>" id="<%= id %>" <%= checked %> acronym="<%= acronym %>" />
<% if (hasCloseButton === true) { %>
<div <% if (isbold != '') { %> class="sf-list_label sf-authors-bold" <% } else { %> class="sf-list_label" style="margin-bottom:5px"<% } %>><%= valName %><span class="facet-count"><%= valCount %></span> <span class="fal fa-times-circle facet-value_toggle purple-color"></span></div> <%= detail%>
<% } else { %>
<label <%= title%> for="<%= id %>" <% if (isbold != '') { %> class="sf-list_label sf-authors-bold" <% } else { %> class="sf-list_label" <% } %>><%= valName %> <span class="facet-count"><%= valCount %></span></label> <%= detail%>
<% } %>
</li>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="more-term-facet-value">
<li class="selection-list_list-item" style="<%= display %>">
<input id="<%= labelid %>" class="selection-list_checkbox" aria-label="<%= dataValue %>" type="checkbox" name="<%= name %>" data-value="<%= dataValue %>" <%= checked %> <%= boxstyle %>/><div class="selection-list_link" name="text-<%= name %>" data-value="<%= dataValue %>" <%= clazz %>><label for="<%= labelid %>" style="font-weight:normal;margin-bottom:0px;"><%= valName %><% if (valCount != "") { %> <span class="more-facet-count"><%= valCount %></span><% } %></label></div><% if (isx === true) { %><a href="#" aria-label="selection expander" class="selection-list_expander <%= inputname%>-expandin" aria-controls="topic-list"><svg class="selection-list_arrow"><use xlink:href="#right-arrow" /></svg></a><% } %>
</li>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="more-term-selected">
<div class="selected-facet" data-topic="<%= finalTopic %>">
<%= val %>
<a href="#" name="selected-x" aria-label="Remove <%= dataValue %> filter" data-value="<%= dataValue %>" count="<%= cnt %>" class="selected-facet_close" role="button" tabindex="0"><span class="fal fa-times-circle purple-color" aria-hidden="true"></span></a>
</div>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-facet-class">
class=""
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-facet-style-normal">
style="font-weight:normal"
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="search-result-facet-sort-popup">
<p>
<input type="radio" id='<%= name %>:item-order:ascending' name="facetSortBy" value='<%= name %>:item-order:ascending' >
<label for='<%= name %>:item-order:ascending'><%= label %> ascending</label><br>
<input type="radio" id='<%= name %>:item-order:descending' name="facetSortBy" value='<%= name %>:item-order:descending' >
<label for='<%= name %>:item-order:descending'><%= label %> descending</label><br>
<input type="radio" id='<%= name %>:frequency-order:ascending' name="facetSortBy" value='<%= name %>:frequency-order:ascending' >
<label for='<%= name %>:frequency-order:ascending'>Frequency ascending</label><br>
<input type="radio" id='<%= name %>:frequency-order:descending' name="facetSortBy" value='<%= name %>:frequency-order:descending'>
<label for='<%= name %>:frequency-order:descending'>Frequency descending</label>
</p>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="filter-selected">
<li class="label filter-tag filter-tag--<%= filterType %>"> <%= filterValue %> <a class="inline-dismiss"><span name="filterSelected" id="<%= filterId %>" class="fal fa-times purple-color" data-value="<%= filterValue %>"></span></a></li>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="filter-search">
<li class="filter-search label filter-tag filter-tag--<%= filterType %>"> <%= filterLabel %> <a class="inline-dismiss"><span name="filterSelected" id="<%= filterId %>" class="fal fa-times purple-color" data-value="<%= filterValue %>"></span></a></li>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="publication-sort-template">
<button class="sf-sort-toggle"><i class="fas fa-sort"></i><span class="sr-only">sort</span></button>
<div class="sf-sort-popup">
<ul>
<li class="active"><a href="#" name="sort-<%= type%>" data-value="<%= type%>:frequency-order:descending">Article Count</a></li>
<li><a href="#" name="sort-<%= type%>" data-value="<%= type%>:item-order:ascending">Alphabetical A>Z</a></li>
<li><a href="#" name="sort-<%= type%>" data-value="<%= type%>:item-order:descending">Alphabetical Z>A</a></li>
</ul>
</div>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="author-topic-sort-template">
<button class="sf-sort-toggle"><i class="fas fa-sort"></i><span class="sr-only">sort</span></button>
<div class="sf-sort-popup">
<ul>
<li class="active"><a href="#" name="sort-<%= type%>" data-value="<%= type%>:frequency-order:descending">Article Count</a></li>
<li><a href="#" name="sort-<%= type%>" data-value="<%= type%>:item-order:ascending">Alphabetical A>Z</a></li>
<li><a href="#" name="sort-<%= type%>" data-value="<%= type%>:item-order:descending">Alphabetical Z>A</a></li>
</ul>
</div>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="year-sort-template">
<button class="sf-sort-toggle"><i class="fas fa-sort"></i><span class="sr-only">sort</span></button>
<div class="sf-sort-popup">
<ul>
<li class="active"><a href="#" name="sort-year" data-value="year:item-order:descending">Newest date first</a></li>
<li><a href="#" name="sort-year" data-value="year:item-order:ascending">Oldest date first</a></li>
<li><a href="#" name="sort-year" data-value="year:frequency-order:descending">Article Count</a></li>
</ul>
</div>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="more-pop-up-template">
<%= values%>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="loading-gif-template">
<li><img style="position:center; display:none;" src="/images/ajax-loader.gif"/></li>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="all-plus-separator-template">
<li class="sf-select-all"><input id="<%= allId %>" type="checkbox" > <label for="<%= allId %>">All</label></li>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="more-topic-column-header">
<div class="selection-list_header"><%= name %></div>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/template" id="loader">
<div class="progress">
<div class="progress-bar progress-bar-striped active" role="progress-bar" id="progress-<%= allId %>"></div>
</div>
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript">
document.addEventListener('DOMContentLoaded', function() {
if (location.hash.indexOf("figanchor") != -1) {
let figHash = location.hash;
$("#figurestablink").click();
window.location.hash = figHash;
$(location.hash).get(0).scrollIntoView({behavior: "smooth"});
}
// Populate recent pages
if (typeof populateRecentPages === 'function') {
populateRecentPages();
}
// Lazy load images
$("img").removeClass("lazyimg").unveil(100);
});
</script>
<script nonce="Fk4e6IQwolG8Ayn1RuigR4YM/sozWxbMHhEK4OKVkG0=" type="text/javascript">
var gaAcct = "UA-1200622-15";
function downloadJSAtOnload() {
var element = document.createElement("script");
element.src = "/js/loadJS.js";
document.body.appendChild(element);
}
if (window.addEventListener)
window.addEventListener("load", downloadJSAtOnload, false);
else if (window.attachEvent)
window.attachEvent("onload", downloadJSAtOnload);
else window.onload = downloadJSAtOnload;
</script>
</body>
</html>
